addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.11.1")
addSbtPlugin("com.github.sbt" % "sbt-cpd" % "2.0.0")
addSbtPlugin("com.waioeka.sbt" % "cucumber-plugin" % "0.3.1")
addSbtPlugin("com.github.sbt" % "sbt-jacoco" % "3.0.3")
