pages = [{"l":"index.html#","e":false,"i":"","n":"Prolog-as-ScalaDSL","t":"Prolog-as-ScalaDSL","d":"","k":"static","x":""},
{"l":"io/github/kelvindev15.html#","e":false,"i":"","n":"io.github.kelvindev15","t":"io.github.kelvindev15","d":"","k":"package","x":""},
{"l":"io/github/kelvindev15.html#Query-0","e":false,"i":"","n":"Query","t":"Query","d":"io.github.kelvindev15","k":"type","x":""},
{"l":"io/github/kelvindev15.html#Substitution-0","e":false,"i":"","n":"Substitution","t":"Substitution","d":"io.github.kelvindev15","k":"type","x":""},
{"l":"io/github/kelvindev15/prolog.html#","e":false,"i":"","n":"io.github.kelvindev15.prolog","t":"io.github.kelvindev15.prolog","d":"","k":"package","x":""},
{"l":"io/github/kelvindev15/prolog/dsl.html#","e":false,"i":"","n":"io.github.kelvindev15.prolog.dsl","t":"io.github.kelvindev15.prolog.dsl","d":"","k":"package","x":""},
{"l":"io/github/kelvindev15/prolog/dsl/PrologDSL.html#","e":false,"i":"","n":"PrologDSL","t":"PrologDSL","d":"io.github.kelvindev15.prolog.dsl","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/dsl/PrologDSL.html#program-d26","e":false,"i":"","n":"program","t":"program(using scope: Any)(): Any","d":"io.github.kelvindev15.prolog.dsl.PrologDSL","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/utils.html#","e":false,"i":"","n":"io.github.kelvindev15.prolog.utils","t":"io.github.kelvindev15.prolog.utils","d":"","k":"package","x":""},
{"l":"io/github/kelvindev15/prolog/utils/BinaryToFlatVisitor.html#","e":false,"i":"","n":"BinaryToFlatVisitor","t":"BinaryToFlatVisitor extends TermVisitor[Iterable[Term]]","d":"io.github.kelvindev15.prolog.utils","k":"class","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#","e":false,"i":"","n":"TermVisitor","t":"TermVisitor[T]","d":"io.github.kelvindev15.prolog.utils","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#visit-fffff64d","e":false,"i":"","n":"visit","t":"visit(constant: Constant): T","d":"io.github.kelvindev15.prolog.utils.TermVisitor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#visit-fffff9c8","e":false,"i":"","n":"visit","t":"visit(atom: Atom): T","d":"io.github.kelvindev15.prolog.utils.TermVisitor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#visit-fffff73c","e":false,"i":"","n":"visit","t":"visit(numeric: Numeric): T","d":"io.github.kelvindev15.prolog.utils.TermVisitor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#visit-525","e":false,"i":"","n":"visit","t":"visit(variable: Variable): T","d":"io.github.kelvindev15.prolog.utils.TermVisitor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#visit-fffff9fe","e":false,"i":"","n":"visit","t":"visit(struct: Struct): T","d":"io.github.kelvindev15.prolog.utils.TermVisitor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#visit-c64","e":false,"i":"","n":"visit","t":"visit(rule: Rule): T","d":"io.github.kelvindev15.prolog.utils.TermVisitor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#visit-bd4","e":false,"i":"","n":"visit","t":"visit(fact: Fact): T","d":"io.github.kelvindev15.prolog.utils.TermVisitor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/utils/TermVisitor.html#visit-99e","e":false,"i":"","n":"visit","t":"visit(binaryRecursiveStruct: BinaryRecursiveStruct): T","d":"io.github.kelvindev15.prolog.utils.TermVisitor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Constant.html#","e":false,"i":"","n":"Constant","t":"Constant extends Term","d":"io.github.kelvindev15.prolog","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Constant.html#value-0","e":false,"i":"","n":"value","t":"value: Any","d":"io.github.kelvindev15.prolog.Constant","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$.html#","e":false,"i":"","n":"Constant","t":"Constant","d":"io.github.kelvindev15.prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$.html#apply-fffff707","e":false,"i":"","n":"apply","t":"apply(value: Any): Constant","d":"io.github.kelvindev15.prolog.Constant","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Atom$.html#","e":false,"i":"","n":"Atom","t":"Atom","d":"io.github.kelvindev15.prolog.Constant","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Atom$.html#apply-fffff6b0","e":false,"i":"","n":"apply","t":"apply(value: String): Atom","d":"io.github.kelvindev15.prolog.Constant.Atom","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Atom.html#","e":false,"i":"","n":"Atom","t":"Atom extends Constant, Struct","d":"io.github.kelvindev15.prolog.Constant","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Atom.html#arguments-0","e":false,"i":"","n":"arguments","t":"arguments: Iterable[Term]","d":"io.github.kelvindev15.prolog.Constant.Atom","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Atom.html#arity-0","e":false,"i":"","n":"arity","t":"arity: Int","d":"io.github.kelvindev15.prolog.Constant.Atom","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Atom.html#functor-0","e":false,"i":"","n":"functor","t":"functor: Atom","d":"io.github.kelvindev15.prolog.Constant.Atom","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Atom.html#value-0","e":false,"i":"","n":"value","t":"value: String","d":"io.github.kelvindev15.prolog.Constant.Atom","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Numeric$.html#","e":false,"i":"","n":"Numeric","t":"Numeric","d":"io.github.kelvindev15.prolog.Constant","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Numeric$.html#apply-ffc","e":false,"i":"","n":"apply","t":"apply(value: AnyVal): Numeric","d":"io.github.kelvindev15.prolog.Constant.Numeric","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Numeric.html#","e":false,"i":"","n":"Numeric","t":"Numeric extends Constant","d":"io.github.kelvindev15.prolog.Constant","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Constant$$Numeric.html#value-0","e":false,"i":"","n":"value","t":"value: AnyVal","d":"io.github.kelvindev15.prolog.Constant.Numeric","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$.html#","e":false,"i":"","n":"Goals","t":"Goals","d":"io.github.kelvindev15.prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Conjunction$.html#","e":false,"i":"","n":"Conjunction","t":"Conjunction","d":"io.github.kelvindev15.prolog.Goals","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Conjunction$.html#apply-437","e":false,"i":"","n":"apply","t":"apply(args: Term*): Conjunction","d":"io.github.kelvindev15.prolog.Goals.Conjunction","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Conjunction$.html#unapply-ff","e":false,"i":"","n":"unapply","t":"unapply(conjunction: Conjunction): Option[(Term, Term)]","d":"io.github.kelvindev15.prolog.Goals.Conjunction","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Conjunction$.html#wrapIfNecessary-fffff3b7","e":false,"i":"","n":"wrapIfNecessary","t":"wrapIfNecessary(args: Term*): Term","d":"io.github.kelvindev15.prolog.Goals.Conjunction","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Conjunction.html#","e":false,"i":"","n":"Conjunction","t":"Conjunction extends BinaryRecursiveStruct","d":"io.github.kelvindev15.prolog.Goals","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Conjunction.html#functor-0","e":false,"i":"","n":"functor","t":"functor: Atom","d":"io.github.kelvindev15.prolog.Goals.Conjunction","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Disjunction$.html#","e":false,"i":"","n":"Disjunction","t":"Disjunction","d":"io.github.kelvindev15.prolog.Goals","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Disjunction$.html#apply-437","e":false,"i":"","n":"apply","t":"apply(args: Term*): Conjunction","d":"io.github.kelvindev15.prolog.Goals.Disjunction","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Disjunction$.html#unapply-fffff60b","e":false,"i":"","n":"unapply","t":"unapply(disjunction: Disjunction): Option[(Term, Term)]","d":"io.github.kelvindev15.prolog.Goals.Disjunction","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Disjunction$.html#wrapIfNecessary-fffff3b7","e":false,"i":"","n":"wrapIfNecessary","t":"wrapIfNecessary(args: Term*): Term","d":"io.github.kelvindev15.prolog.Goals.Disjunction","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Disjunction.html#","e":false,"i":"","n":"Disjunction","t":"Disjunction extends BinaryRecursiveStruct","d":"io.github.kelvindev15.prolog.Goals","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Goals$$Disjunction.html#functor-0","e":false,"i":"","n":"functor","t":"functor: Atom","d":"io.github.kelvindev15.prolog.Goals.Disjunction","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Language$.html#","e":false,"i":"","n":"Language","t":"Language","d":"io.github.kelvindev15.prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Language$$Builtins$.html#","e":false,"i":"","n":"Builtins","t":"Builtins","d":"io.github.kelvindev15.prolog.Language","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$.html#","e":false,"i":"","n":"Prolog","t":"Prolog","d":"io.github.kelvindev15.prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Functors$.html#","e":false,"i":"","n":"Functors","t":"Functors","d":"io.github.kelvindev15.prolog.Prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Functors$.html#CLAUSE-0","e":false,"i":"","n":"CLAUSE","t":"CLAUSE: Atom","d":"io.github.kelvindev15.prolog.Prolog.Functors","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Functors$.html#CONS-0","e":false,"i":"","n":"CONS","t":"CONS: Atom","d":"io.github.kelvindev15.prolog.Prolog.Functors","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Functors$.html#EMPTY_LIST-0","e":false,"i":"","n":"EMPTY_LIST","t":"EMPTY_LIST: Atom","d":"io.github.kelvindev15.prolog.Prolog.Functors","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Functors$.html#FAIL-0","e":false,"i":"","n":"FAIL","t":"FAIL: Atom","d":"io.github.kelvindev15.prolog.Prolog.Functors","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Functors$.html#GOAL_CONJUNCTION-0","e":false,"i":"","n":"GOAL_CONJUNCTION","t":"GOAL_CONJUNCTION: Atom","d":"io.github.kelvindev15.prolog.Prolog.Functors","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Functors$.html#GOAL_DISJUNCTION-0","e":false,"i":"","n":"GOAL_DISJUNCTION","t":"GOAL_DISJUNCTION: Atom","d":"io.github.kelvindev15.prolog.Prolog.Functors","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Functors$.html#TRUE-0","e":false,"i":"","n":"TRUE","t":"TRUE: Atom","d":"io.github.kelvindev15.prolog.Prolog.Functors","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Syntax$.html#","e":false,"i":"","n":"Syntax","t":"Syntax","d":"io.github.kelvindev15.prolog.Prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Syntax$.html#AtomRegex-0","e":false,"i":"","n":"AtomRegex","t":"AtomRegex: Regex","d":"io.github.kelvindev15.prolog.Prolog.Syntax","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Prolog$$Syntax$.html#VariableRegex-0","e":false,"i":"","n":"VariableRegex","t":"VariableRegex: Regex","d":"io.github.kelvindev15.prolog.Prolog.Syntax","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList.html#","e":false,"i":"","n":"PrologList","t":"PrologList extends RecursiveStruct","d":"io.github.kelvindev15.prolog","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList.html#size-0","e":false,"i":"","n":"size","t":"size: Int","d":"io.github.kelvindev15.prolog.PrologList","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$.html#","e":false,"i":"","n":"PrologList","t":"PrologList","d":"io.github.kelvindev15.prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$.html#apply-fffff1c0","e":false,"i":"","n":"apply","t":"apply(elements: Term*): PrologList","d":"io.github.kelvindev15.prolog.PrologList","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons$.html#","e":false,"i":"","n":"Cons","t":"Cons","d":"io.github.kelvindev15.prolog.PrologList","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons$.html#apply-fffff2a2","e":false,"i":"","n":"apply","t":"apply(head: Term, tail: PrologList): PrologList","d":"io.github.kelvindev15.prolog.PrologList.Cons","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons.html#","e":false,"i":"","n":"Cons","t":"Cons extends PrologList","d":"io.github.kelvindev15.prolog.PrologList","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons.html#arguments-0","e":false,"i":"","n":"arguments","t":"arguments: Iterable[Term]","d":"io.github.kelvindev15.prolog.PrologList.Cons","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons.html#arity-0","e":false,"i":"","n":"arity","t":"arity: Int","d":"io.github.kelvindev15.prolog.PrologList.Cons","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons.html#functor-0","e":false,"i":"","n":"functor","t":"functor: Atom","d":"io.github.kelvindev15.prolog.PrologList.Cons","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons.html#head-0","e":false,"i":"","n":"head","t":"head: Term","d":"io.github.kelvindev15.prolog.PrologList.Cons","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons.html#size-0","e":false,"i":"","n":"size","t":"size: Int","d":"io.github.kelvindev15.prolog.PrologList.Cons","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Cons.html#tail-0","e":false,"i":"","n":"tail","t":"tail: PrologList","d":"io.github.kelvindev15.prolog.PrologList.Cons","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Nil$.html#","e":false,"i":"","n":"Nil","t":"Nil extends PrologList","d":"io.github.kelvindev15.prolog.PrologList","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Nil$.html#arguments-0","e":false,"i":"","n":"arguments","t":"arguments: Iterable[Term]","d":"io.github.kelvindev15.prolog.PrologList.Nil","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Nil$.html#arity-0","e":false,"i":"","n":"arity","t":"arity: Int","d":"io.github.kelvindev15.prolog.PrologList.Nil","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Nil$.html#functor-0","e":false,"i":"","n":"functor","t":"functor: Atom","d":"io.github.kelvindev15.prolog.PrologList.Nil","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/PrologList$$Nil$.html#size-0","e":false,"i":"","n":"size","t":"size: Int","d":"io.github.kelvindev15.prolog.PrologList.Nil","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct.html#","e":false,"i":"","n":"RecursiveStruct","t":"RecursiveStruct extends Struct","d":"io.github.kelvindev15.prolog","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct.html#linearizedArguments-0","e":false,"i":"","n":"linearizedArguments","t":"linearizedArguments: Iterable[Term]","d":"io.github.kelvindev15.prolog.RecursiveStruct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$.html#","e":false,"i":"","n":"RecursiveStruct","t":"RecursiveStruct","d":"io.github.kelvindev15.prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct$.html#","e":false,"i":"","n":"BinaryRecursiveStruct","t":"BinaryRecursiveStruct","d":"io.github.kelvindev15.prolog.RecursiveStruct","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct$.html#fold-fffff7df","e":false,"i":"","n":"fold","t":"fold[T <: BinaryRecursiveStruct](struct: (Term, Term) => T)(args: Term*): T","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct$.html#wrapIfNecessary-106","e":false,"i":"","n":"wrapIfNecessary","t":"wrapIfNecessary(struct: Seq[Term] => BinaryRecursiveStruct)(args: Term*): Term","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct$$Tuple$.html#","e":false,"i":"","n":"Tuple","t":"Tuple","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct$$Tuple$.html#unapply-3c8","e":false,"i":"","n":"unapply","t":"unapply(tuple: BinaryRecursiveStruct): Option[(Term, Term)]","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct.Tuple","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct.html#","e":false,"i":"","n":"BinaryRecursiveStruct","t":"BinaryRecursiveStruct extends RecursiveStruct","d":"io.github.kelvindev15.prolog.RecursiveStruct","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct.html#arguments-0","e":false,"i":"","n":"arguments","t":"arguments: Iterable[Term]","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct.html#arity-0","e":false,"i":"","n":"arity","t":"arity: Int","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct.html#first-0","e":false,"i":"","n":"first","t":"first: Term","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct.html#left-0","e":false,"i":"","n":"left","t":"left: Term","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct.html#right-0","e":false,"i":"","n":"right","t":"right: Term","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/RecursiveStruct$$BinaryRecursiveStruct.html#second-0","e":false,"i":"","n":"second","t":"second: Term","d":"io.github.kelvindev15.prolog.RecursiveStruct.BinaryRecursiveStruct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Struct.html#","e":false,"i":"","n":"Struct","t":"Struct extends Term","d":"io.github.kelvindev15.prolog","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Struct.html#arguments-0","e":false,"i":"","n":"arguments","t":"arguments: Iterable[Term]","d":"io.github.kelvindev15.prolog.Struct","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Struct.html#arity-0","e":false,"i":"","n":"arity","t":"arity: Int","d":"io.github.kelvindev15.prolog.Struct","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Struct.html#functor-0","e":false,"i":"","n":"functor","t":"functor: Atom","d":"io.github.kelvindev15.prolog.Struct","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$.html#","e":false,"i":"","n":"Struct","t":"Struct","d":"io.github.kelvindev15.prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$.html#apply-fffff8cb","e":false,"i":"","n":"apply","t":"apply(functor: Atom, args: Term*): Struct","d":"io.github.kelvindev15.prolog.Struct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$.html#quoteIfFunctorIsMalformed-fffff2ca","e":false,"i":"","n":"quoteIfFunctorIsMalformed","t":"quoteIfFunctorIsMalformed(functor: String): String","d":"io.github.kelvindev15.prolog.Struct","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Args$.html#","e":false,"i":"","n":"Args","t":"Args","d":"io.github.kelvindev15.prolog.Struct","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Args$.html#unapply-428","e":false,"i":"","n":"unapply","t":"unapply(struct: Struct): Option[Iterable[Term]]","d":"io.github.kelvindev15.prolog.Struct.Args","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Fact$.html#","e":false,"i":"","n":"Fact","t":"Fact","d":"io.github.kelvindev15.prolog.Struct","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Fact$.html#apply-fffff236","e":false,"i":"","n":"apply","t":"apply(head: Struct): Fact","d":"io.github.kelvindev15.prolog.Struct.Fact","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Fact.html#","e":false,"i":"","n":"Fact","t":"Fact extends Rule","d":"io.github.kelvindev15.prolog.Struct","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Fact.html#body-0","e":false,"i":"","n":"body","t":"body: Term","d":"io.github.kelvindev15.prolog.Struct.Fact","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Functor$.html#","e":false,"i":"","n":"Functor","t":"Functor","d":"io.github.kelvindev15.prolog.Struct","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Functor$.html#unapply-428","e":false,"i":"","n":"unapply","t":"unapply(struct: Struct): Option[Atom]","d":"io.github.kelvindev15.prolog.Struct.Functor","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Rule$.html#","e":false,"i":"","n":"Rule","t":"Rule","d":"io.github.kelvindev15.prolog.Struct","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Rule$.html#apply-fffffa3b","e":false,"i":"","n":"apply","t":"apply(head: Struct, args: Term*): Rule","d":"io.github.kelvindev15.prolog.Struct.Rule","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Rule.html#","e":false,"i":"","n":"Rule","t":"Rule extends Struct","d":"io.github.kelvindev15.prolog.Struct","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Rule.html#arguments-0","e":false,"i":"","n":"arguments","t":"arguments: Iterable[Term]","d":"io.github.kelvindev15.prolog.Struct.Rule","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Rule.html#arity-0","e":false,"i":"","n":"arity","t":"arity: Int","d":"io.github.kelvindev15.prolog.Struct.Rule","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Rule.html#body-0","e":false,"i":"","n":"body","t":"body: Term","d":"io.github.kelvindev15.prolog.Struct.Rule","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Rule.html#functor-0","e":false,"i":"","n":"functor","t":"functor: Atom","d":"io.github.kelvindev15.prolog.Struct.Rule","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Struct$$Rule.html#head-0","e":false,"i":"","n":"head","t":"head: Struct","d":"io.github.kelvindev15.prolog.Struct.Rule","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Term.html#","e":false,"i":"","n":"Term","t":"Term extends Visitable","d":"io.github.kelvindev15.prolog","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Term.html#isGround-0","e":false,"i":"","n":"isGround","t":"isGround: Boolean","d":"io.github.kelvindev15.prolog.Term","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Term.html#variables-0","e":false,"i":"","n":"variables","t":"variables: Iterable[Variable]","d":"io.github.kelvindev15.prolog.Term","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Variable.html#","e":false,"i":"","n":"Variable","t":"Variable extends Term","d":"io.github.kelvindev15.prolog","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Variable.html#isAnonymous-0","e":false,"i":"","n":"isAnonymous","t":"isAnonymous: Boolean","d":"io.github.kelvindev15.prolog.Variable","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Variable.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"io.github.kelvindev15.prolog.Variable","k":"val","x":""},
{"l":"io/github/kelvindev15/prolog/Variable$.html#","e":false,"i":"","n":"Variable","t":"Variable","d":"io.github.kelvindev15.prolog","k":"object","x":""},
{"l":"io/github/kelvindev15/prolog/Variable$.html#anonymous-f92","e":false,"i":"","n":"anonymous","t":"anonymous(): Variable","d":"io.github.kelvindev15.prolog.Variable","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Variable$.html#apply-44d","e":false,"i":"","n":"apply","t":"apply(name: String): Variable","d":"io.github.kelvindev15.prolog.Variable","k":"def","x":""},
{"l":"io/github/kelvindev15/prolog/Visitable.html#","e":false,"i":"","n":"Visitable","t":"Visitable","d":"io.github.kelvindev15.prolog","k":"trait","x":""},
{"l":"io/github/kelvindev15/prolog/Visitable.html#accept-c53","e":false,"i":"","n":"accept","t":"accept[T](visitor: TermVisitor[T]): T","d":"io.github.kelvindev15.prolog.Visitable","k":"def","x":""},
{"l":"io/github/kelvindev15/PrologProgram.html#","e":false,"i":"","n":"PrologProgram","t":"PrologProgram","d":"io.github.kelvindev15","k":"class","x":""},
{"l":"io/github/kelvindev15/PrologProgram.html#solve-fffffe6d","e":false,"i":"","n":"solve","t":"solve(query: Query): Solution","d":"io.github.kelvindev15.PrologProgram","k":"def","x":""},
{"l":"io/github/kelvindev15/Solution.html#","e":false,"i":"","n":"Solution","t":"Solution","d":"io.github.kelvindev15","k":"enum","x":""},
{"l":"io/github/kelvindev15/Solution$$Yes.html#","e":false,"i":"","n":"Yes","t":"Yes(substitution: Substitution)","d":"io.github.kelvindev15.Solution","k":"case","x":""},
{"l":"io/github/kelvindev15/Solution.html#No-0","e":false,"i":"","n":"No","t":"No extends Solution","d":"io.github.kelvindev15.Solution","k":"case","x":""},
{"l":"io/github/kelvindev15/Solution$$Yes.html#","e":false,"i":"","n":"Yes","t":"Yes(substitution: Substitution)","d":"io.github.kelvindev15.Solution","k":"case","x":""}];